"""Voice channel helpers: TTS-safe text sanitation, the FIXED approval
dialogue messages, and the exact-match option normalizer.

The approval decision itself is deliberately deterministic: the LLM may
explain and re-ask, but only a 1:1 option match (this module's normalize())
executes a decision — a misheard sentence can never approve anything."""

import re

# ── fixed messages (never generated by the LLM) ─────────────────────────────
APPROVAL_OPTIONS = "Would you like to {options} for it?"
APPROVAL_CONFIRM = "Okay. I registered '{choice}' for task '{title}'."
APPROVAL_GONE = "That approval is no longer pending. Nothing was changed."

# Hermes's own server-side aliases (api_server.py) — accepted as exact matches
# whenever 'once' is among the offered choices.
CHOICE_ALIASES = {"approve": "once", "approved": "once", "allow": "once"}


def options_sentence(choices: list[str]) -> str:
    """['once','session','always','deny'] → 'once, session, always or deny'."""
    if len(choices) == 1:
        return choices[0]
    return ", ".join(choices[:-1]) + " or " + choices[-1]


def normalize(text: str) -> str:
    """Lowercase, strip punctuation/whitespace — the 1:1 match key."""
    return re.sub(r"[^a-z0-9 ]", "", (text or "").lower()).strip()


def match_choice(text: str, choices: list[str]) -> str | None:
    """Return the matched choice word, or None. Exact match only."""
    n = normalize(text)
    for c in choices:
        if n == normalize(c):
            return c
    alias = CHOICE_ALIASES.get(n)
    if alias and alias in choices:
        return alias
    return None


# ── TTS-safe text ────────────────────────────────────────────────────────────
_KEEP = set(" .,?!;:'\"()%/+-@$€\n")


def speakable(text: str) -> str:
    """Strip markdown, emojis, tables and links down to plain sentences a TTS
    engine reads naturally. Letters/digits (any language) and simple
    punctuation survive; everything else becomes a space."""
    t = re.sub(r"```.*?```", " ", text or "", flags=re.S)
    t = t.replace("`", "")
    t = re.sub(r"!\[[^\]]*\]\([^)]*\)", " ", t)              # images
    t = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", t)           # links → label
    t = re.sub(r"https?://\S+", " a link ", t)
    t = re.sub(r"^\s*\|.*\|\s*$", " ", t, flags=re.M)        # table rows
    t = re.sub(r"^\s*#{1,6}\s*", "", t, flags=re.M)          # headings
    t = re.sub(r"^\s*(?:[-*•]|\d+[.)])\s+", "", t, flags=re.M)  # bullets
    t = re.sub(r"[*_~>|#]", " ", t)                          # leftover markdown
    t = "".join(ch if (ch.isalnum() or ch in _KEEP) else " " for ch in t)
    t = re.sub(r"[ \t]+", " ", t)
    t = re.sub(r"\s*\n+\s*", ". ", t)                        # newlines → pauses
    t = re.sub(r"\.\s*\.(\s*\.)*", ".", t)                   # collapse dots
    t = re.sub(r"\s+([.,?!;:])", r"\1", t)
    return t.strip()


def sentences(text: str) -> list[str]:
    """Split into speakable chunks for pseudo-streaming (one SSE chunk each)."""
    parts = re.findall(r"[^.?!]+[.?!]*\s*", text)
    return [p for p in (s.strip() + " " for s in parts) if p.strip()]
