"""Voice channel helpers: TTS-safe text sanitation, the FIXED approval
dialogue messages, and the exact-match option normalizer.

The approval decision itself is deliberately deterministic: the LLM may
explain and re-ask, but only a 1:1 option match (this module's normalize())
executes a decision — a misheard sentence can never approve anything.

Also home of VoiceChannel: the delivery state shared by every voice consumer
(the OpenAI-compatible HTTP front door in gateway/api.py and the in-process
voicebot package)."""

import asyncio
import re

# ── fixed messages (never generated by the LLM) ─────────────────────────────
APPROVAL_OPTIONS = "Would you like to {options} for it?"
APPROVAL_CONFIRM = "Okay. I registered '{choice}' for task '{title}'."
APPROVAL_GONE = "That approval is no longer pending. Nothing was changed."

# Hermes's own server-side aliases (api_server.py) — accepted as exact matches
# whenever 'once' is among the offered choices.
CHOICE_ALIASES = {"approve": "once", "approved": "once", "allow": "once"}


def options_sentence(choices: list[str]) -> str:
    """['once','session','always','deny'] → 'once, session, always or deny'."""
    if len(choices) == 1:
        return choices[0]
    return ", ".join(choices[:-1]) + " or " + choices[-1]


def normalize(text: str) -> str:
    """Lowercase, strip punctuation/whitespace — the 1:1 match key."""
    return re.sub(r"[^a-z0-9 ]", "", (text or "").lower()).strip()


def match_choice(text: str, choices: list[str]) -> str | None:
    """Return the matched choice word, or None. Exact match only."""
    n = normalize(text)
    for c in choices:
        if n == normalize(c):
            return c
    alias = CHOICE_ALIASES.get(n)
    if alias and alias in choices:
        return alias
    return None


# ── TTS-safe text ────────────────────────────────────────────────────────────
_KEEP = set(" .,?!;:'\"()%/+-@$€\n")


def speakable(text: str) -> str:
    """Strip markdown, emojis, tables and links down to plain sentences a TTS
    engine reads naturally. Letters/digits (any language) and simple
    punctuation survive; everything else becomes a space."""
    t = re.sub(r"```.*?```", " ", text or "", flags=re.S)
    t = t.replace("`", "")
    t = re.sub(r"!\[[^\]]*\]\([^)]*\)", " ", t)              # images
    t = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", t)           # links → label
    t = re.sub(r"https?://\S+", " a link ", t)
    t = re.sub(r"^\s*\|.*\|\s*$", " ", t, flags=re.M)        # table rows
    t = re.sub(r"^\s*#{1,6}\s*", "", t, flags=re.M)          # headings
    t = re.sub(r"^\s*(?:[-*•]|\d+[.)])\s+", "", t, flags=re.M)  # bullets
    t = re.sub(r"[*_~>|#]", " ", t)                          # leftover markdown
    t = "".join(ch if (ch.isalnum() or ch in _KEEP) else " " for ch in t)
    t = re.sub(r"[ \t]+", " ", t)
    t = re.sub(r"\s*\n+\s*", ". ", t)                        # newlines → pauses
    t = re.sub(r"\.\s*\.(\s*\.)*", ".", t)                   # collapse dots
    t = re.sub(r"\s+([.,?!;:])", r"\1", t)
    return t.strip()


def sentences(text: str) -> list[str]:
    """Split into speakable chunks for pseudo-streaming (one SSE chunk each)."""
    parts = re.findall(r"[^.?!]+[.?!]*\s*", text)
    return [p for p in (s.strip() + " " for s in parts) if p.strip()]


# ── shared voice-channel state ───────────────────────────────────────────────
class VoiceChannel:
    """Which Home-thread assistant messages have been spoken, and which pending
    approvals already beeped. ONE instance lives on App and is shared by the
    HTTP front door and the in-process voicebot, so a message is delivered
    exactly once no matter which consumer picks it up first."""

    THREAD = 1  # Home — voice and dashboard share one conversation

    def __init__(self, app):
        self.app = app
        self.lock = asyncio.Lock()
        self._cursor: int | None = None
        self._beeped: set[int] = set()
        self._ui_delivered: set[int] = set()  # replies to TYPED input — never speak

    @property
    def speak_text_replies(self) -> bool:
        """voice.speak_text_replies, read LIVE from config.yaml — so both the
        speech_mode kernel tool and `./lityctl set` take effect immediately.
        False (default): typed input → reply in the UI only. True: spoken too."""
        from .modules import modules_cfg
        return bool(modules_cfg(self.app, "voice").get("speak_text_replies", False))

    def note_text_reply(self, mid: int):
        """Kernel calls this for every assistant reply to a TYPED message.
        Unless merge mode is on, the reply is already on screen — mark it so
        the voicebot skips it (the cursor still advances past it)."""
        if not self.speak_text_replies:
            self._ui_delivered.add(mid)

    def mute(self, mid: int):
        """This message must never be spoken (quiet hours): it stays on screen,
        the cursor advances past it like any delivered reply."""
        self._ui_delivered.add(mid)

    async def _max_msg_id(self) -> int:
        row = await self.app.db.fetchone(
            "SELECT COALESCE(MAX(id),0) AS m FROM messages WHERE thread_id=?",
            (self.THREAD,))
        return int(row["m"])

    async def init_cursor(self):
        """History from before boot is never re-spoken."""
        self._cursor = await self._max_msg_id()

    async def _unheard_locked(self) -> list[str]:
        """Assistant messages (kernel replies, relayed task results) the voice
        channel hasn't delivered yet, as speakable text. Advances the cursor —
        each message is spoken exactly once. 'event' rows (approvals) are
        acknowledged but never spoken: they beep instead."""
        if self._cursor is None:
            self._cursor = await self._max_msg_id()
        rows = await self.app.db.fetchall(
            "SELECT id, content FROM messages WHERE thread_id=? AND role='assistant' "
            "AND id>? ORDER BY id", (self.THREAD, self._cursor))
        self._cursor = await self._max_msg_id()
        rows = [r for r in rows if r["id"] not in self._ui_delivered]
        self._ui_delivered = {i for i in self._ui_delivered if i > self._cursor}
        return [t for t in (speakable(r["content"]) for r in rows) if t]

    async def unheard(self) -> list[str]:
        async with self.lock:
            return await self._unheard_locked()

    async def turn(self, text: str) -> str:
        """One voice turn: hand the utterance to the kernel, return this turn's
        answer plus any not-yet-spoken task results, ready for TTS."""
        async with self.lock:
            await self.app.kernel.on_user_message(self.THREAD, text, source="voice")
            parts = await self._unheard_locked()
        return " ".join(parts) or "Okay."

    # -- approval beeps: two dedupe paths over one set ------------------------
    def approval_beep_poll(self, pending_ids: set[int]) -> bool:
        """HTTP polling path: True once per batch of NEW pending approvals."""
        new = pending_ids - self._beeped
        self._beeped = pending_ids  # forget resolved, remember beeped
        return bool(new)

    def should_beep(self, approval_id: int) -> bool:
        """Event path (in-process announcer): True once per approval id."""
        if approval_id in self._beeped:
            return False
        self._beeped.add(approval_id)
        return True

    def forget_approval(self, approval_id: int):
        self._beeped.discard(approval_id)
